### PR TITLE
fix: windows path sep in source code not compatible with webpack

### PR DESCRIPTION
**Pull request by ahungrynoob**

### CODE REVIEW

**Comment by ahungrynoob** [comment]
path like `.\aaa\bbb\ccc` in source code is not supported by webpack. it should use posix path.

**Comment by PowerfulPony** [comment]
@ahungrynoob 
Where and what is the problem?
assets.path is taken from the one that gets into through the loader, i.e. the one indicated in the project

**Comment by ahungrynoob** [comment]
@PowerfulPony Sorry for the late response. The problem is at this line https://github.com/PowerfulPony/lottie-web-webpack-loader/blob/a9f0aefc27105eb64d5bca3474d4711fd180173b/src/index.js#L27. We create a platform-relevant path here. It's ok in most cases. 
Here we write the platform-relevant path into the source code text in our loader: https://github.com/PowerfulPony/lottie-web-webpack-loader/blob/a9f0aefc27105eb64d5bca3474d4711fd180173b/src/index.js#L58.
When we write the platform-relevant path into our source code text, it will cause webpack not able to understand the import clause. The import path in source code text should be posix like.

**Comment by ahungrynoob** [comment]
This is the error message from webpack when loading source files that use windows-like path:
```bash
Module not found: Error: Can't resolve '.\images\light.png' in 'C:\Users\xxx'
Did you mean './.\images\light.png'?
Requests that should resolve in the current directory need to start with './'.
```

**Review by PowerfulPony — APPROVED** [review]

**Pull request merged**
